{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "7820f1ba",
   "metadata": {},
   "source": [
    "# Planetary Motion\n",
    "## by Aahan Arakkal, Tess Bentley, Toby Clifft, Dante du Preez and Diana Yuan (the Elliptical Explorers)\n",
    "\n",
    "## Introduction\n",
    "\n",
    "In this project, we explore the motion of planets through a vast range of numerical techniques. We start by verifying the accuracy of the velocity Verlet algorithm in solving Newton's equations of motion for a one-dimensional harmonic oscillator. \n",
    "Following this, we estimate how the Earth moves around the sun by simulating an earth-like planet's orbit given certain assumptions, which are stated later on.\n",
    "Our fourth section looks at how varying starting conditions can lead to different orbital shapes: ellipses, hyperbolae and, in a specific case, a parabola. For bounded elliptical trajectories we compute perihelion, aphelion, eccentricity, and\n",
    "other orbital parameters to further explore what determines the shape of an orbit. We also examined how escape velocity is determined from energy considerations, comparing our numerical results with theoretical predictions.\n",
    "Finally, our extension looks at the prediction of solar eclipses. We extend our simulation to a three-body problem involving the Sun, Earth and Moon; modelling their motion from given starting conditions to figure out when they will align\n",
    "to form an eclipse, then identifying which type of eclipse occurs.\n",
    "\n",
    "## Constants\n",
    "The constants which we will use throughout the project are listed below\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2fe80548",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Gravitational constant\n",
    "G = 6.67348e-11              # (in m^3 / kgs^2 )\n",
    "\n",
    "# Sun values\n",
    "m_sun = 1.988420392e30       # Mass of sun (in kg)\n",
    "r_sun = 696340e3             # Radius of sun (in m)\n",
    "\n",
    "# Earth values\n",
    "m_earth = 5.972000000e24     # Mass of Earth (in kg)\n",
    "r_earth = 6371e3             # Radius of Earth (in m)\n",
    "\n",
    "# Moon values\n",
    "m_moon = 7.345828157e22      # Mass of the Moon (in kg)\n",
    "r_moon = 1737e3              # Radius of the Moon (in m)\n",
    "\n",
    "# Astronomical Constants\n",
    "R = 149.6e9                  # 1AU in meters\n",
    "\n",
    "# Time Values\n",
    "hr1 = 3600                   # Time in 1 Hour\n",
    "yr1 = 365.25*24*3600         # Time in 1 year"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3bace9a9",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "## Libraries\n",
    "Below is a list of all the libraries which must be imported for this project:\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01995407",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy.linalg as lag\n",
    "\n",
    "\n",
    "# Specific to Q9:\n",
    "import pandas as pd\n",
    "import time\n",
    "from datetime import datetime, timedelta\n",
    "from tqdm import tqdm"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a6da290b",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "## Q1\n",
    "This first question compares numerical and analytical solutions to differential equations describing a one-dimensional harmonic oscillator. We go on to plot the particle's motion over time, as well as its phase-space trajectory which shows how velocity varies with displacement.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0c2fb36",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Parameters\n",
    "m = 1.0       \n",
    "k = 1.0   \n",
    "omega = np.sqrt(k/m)\n",
    "\n",
    "# Initial conditions\n",
    "x0 = 1.0      \n",
    "v0 = 0.0      \n",
    "\n",
    "# Max time and step size\n",
    "t_max = 20.0\n",
    "dt = 0.01\n",
    "t = np.arange(0, t_max + dt, dt)\n",
    "N = len(t)\n",
    "\n",
    "# Exact solution\n",
    "x_exact = x0 * np.cos(omega*t) + (v0/omega) * np.sin(omega*t)\n",
    "v_exact = -x0 * omega * np.sin(omega*t) + v0 * np.cos(omega*t)\n",
    "\n",
    "# Plot x(t) \n",
    "plt.figure()\n",
    "plt.plot(t, x_exact, label='Exact x(t)')\n",
    "plt.xlabel('t')\n",
    "plt.ylabel('x')\n",
    "plt.title('Harmonic Oscillator: Position vs Time')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "\n",
    "# Phase-space (x(t), v(t)) comparison \n",
    "plt.figure()\n",
    "plt.plot(x_exact, v_exact, label='Exact (x,v)')\n",
    "plt.xlabel('x')\n",
    "plt.ylabel('v')\n",
    "plt.title('Harmonic Oscillator: Phase-Space Trajectory')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "\n",
    "plt.show()\n",
    "\n",
    "# Create arrays to store the numerical solution\n",
    "x_verlet_alg = np.zeros(N)\n",
    "v_verlet_alg = np.zeros(N)\n",
    "\n",
    "# Set the values we have initially to the first index in the arrays\n",
    "x_verlet_alg[0] = x0\n",
    "v_verlet_alg[0] = v0\n",
    "\n",
    "# The acceleration function\n",
    "def acceleration(x):\n",
    "    return -(k/m) * x\n",
    "\n",
    "# Create a loop to use the verlet algorithm\n",
    "for i in range(N - 1):\n",
    "    current_a = acceleration(x_verlet_alg[i]) #the acceleration currently\n",
    "    updated_x = x_verlet_alg[i] + v_verlet_alg[i]*dt + 0.5*current_a*(dt**2) #the updated position\n",
    "    updated_a = acceleration(updated_x) #the updated acceleration, based on position\n",
    "    updated_v = v_verlet_alg[i] + 0.5*(current_a + updated_a)*dt #the updated velocity, based on acceleration\n",
    "\n",
    "    x_verlet_alg[i+1] = updated_x #store the results in the arrays\n",
    "    v_verlet_alg[i+1] = updated_v\n",
    "\n",
    "# Plot for numerical x(t)\n",
    "plt.figure() \n",
    "plt.plot(t, x_verlet_alg, 'orange', linestyle=':', label='Numerical x(t)')\n",
    "plt.xlabel('t')\n",
    "plt.ylabel('x')\n",
    "plt.title('Harmonic Oscillator: Numerical x(t) with Verlet Algorithm')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "\n",
    "# Plot for numerical (x,v) - the Phase-space\n",
    "plt.figure() \n",
    "plt.plot(x_verlet_alg, v_verlet_alg, 'orange', linestyle=':', label='Numerical (x,v)')\n",
    "plt.xlabel('x')\n",
    "plt.ylabel('v')\n",
    "plt.title('Verlet Solution : (x,v) plot')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "\n",
    "# The comparison plots for x(t)\n",
    "plt.figure()\n",
    "plt.plot(t, x_exact, label='Exact x(t)')\n",
    "plt.plot(t, x_verlet_alg, color='orange', linestyle=':', label='Numerical x(t)')\n",
    "plt.xlabel('t')\n",
    "plt.ylabel('x')\n",
    "plt.title('Exact vs Numerical: x(t) over t')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "\n",
    "# The comparison plots for (x,v) - the Phase-space\n",
    "plt.figure() \n",
    "plt.plot(x_exact, v_exact, label='Exact (x,v)')\n",
    "plt.plot(x_verlet_alg, v_verlet_alg, color='orange', linestyle=':', label='Numerical (x,v)')\n",
    "plt.xlabel('x')\n",
    "plt.ylabel('v')\n",
    "plt.title('Exact vs Numerical: (x,v)')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "\n",
    "plt.show"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ae82b01f",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_7_0.png)\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_7_1.png)\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    <function matplotlib.pyplot.show(close=None, block=None)>\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_7_3.png)\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_7_4.png)\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_7_5.png)\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_7_6.png)\n",
    "    \n",
    "\n",
    "\n",
    "### Graph interpretations q.1:\n",
    "We have simulated the motion of an orbiting planet, using both the exact solution and the numerical solution, using the Verlet Algorithm.\n",
    "Our first two graphs show the exact position x(t), giving us a sinusoidal curve and a phase-space trajectory (x,v), from which we get an elliptical curve. \n",
    "These perfect, smooth shapes demonstrate conservation of energy within our system. Using the Verlet algorithm, for the next two graphs of our numerical solutions, we find that these curves closely follow the previous two respectively.\n",
    "The purpose of using 0.01 as a time step ensures any deviations in the two different solutions are minimised, which allows the numerical solution to mimic the exact orbit over time closely.\n",
    "\n",
    "## Q2\n",
    "We now go on to look at the orbit of an Earth-like planet around the sun. We apply Newton's law of gravitation in a simplified two-body system where the Sun is treated as fixed due to its much greater mass. We restrict the orbital motion to the xy-plane, since angular momentum is conserved. This setup provides a simple, yet fairly accurate, framework for simulating the planet's orbital trajectory.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cc0ec8a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Setup\n",
    "s0 = np.sqrt(G * m_sun / R) # Orbital Speed of the Earth-Like Planet\n",
    "r0 = np.array([R,0]) # Initial position vector of the Planet, Starting on the +ve x axis.\n",
    "v0 = np.array([0, s0]) #Initial velocity vector of the planet (Perpendicular to the radius)\n",
    "\n",
    "t = np.arange(0, yr1+hr1, hr1) # Time Array starting at 0, ending at 1 year, incrementing by an hour.\n",
    "N = len(t) # Number of Increments of array t\n",
    "\n",
    "# Results Storing arrays\n",
    "r = np.zeros((N, 2))\n",
    "v = np.zeros((N,2)) # Both Matrices initialised at 0 to store data.\n",
    "r[0] = r0\n",
    "v[0] = v0\n",
    "\n",
    "# Gravitational Acceleration\n",
    "def gAcceleration(x):\n",
    "    dist = lag.norm(x)\n",
    "    return -G * m_sun * x / dist**3 # By formula\n",
    "\n",
    "# Verlet Integration Loop (variable_np1 = variable_{n+1})\n",
    "a_n = gAcceleration(r[0]) # a_{n} is the initial gravitational acceleration\n",
    "for i in range(N-1):\n",
    "    # Updating Position, Acceleration, Velocity\n",
    "    r_np1 = r[i] + v[i]*hr1 + 0.5*a_n*(hr1**2) # r_{n+1}  is updated\n",
    "    a_np1 = gAcceleration(r_np1) # a_{n+1} is updated\n",
    "    v_np1 = v[i] + 0.5*(a_n + a_np1)*hr1 # v_{n+1} is updated\n",
    "\n",
    "    #Storing Variables\n",
    "    r[i+1] = r_np1\n",
    "    v[i+1] = v_np1\n",
    "    a_n = a_np1\n",
    "\n",
    "# Orbit Plot\n",
    "plt.figure(figsize=(6,6))\n",
    "plt.plot(r[:,0],r[:,1], label='Planet Trajectory')\n",
    "plt.scatter(0,0,color='yellow',s=100,label='Sun')\n",
    "plt.xlabel('x(m)')\n",
    "plt.ylabel('y(m)')\n",
    "plt.title('Simulation of an Earth-Like planets orbit')\n",
    "plt.legend(loc='upper right')\n",
    "plt.axis('equal')\n",
    "plt.grid(True)\n",
    "plt.show()\n",
    "\n",
    "# Radius Over Time\n",
    "plt.figure()\n",
    "plt.plot(t/(24*hr1), lag.norm(r, axis=1))\n",
    "plt.xlabel('Time (Days)')\n",
    "plt.ylabel('Radius deviation from initial value (m)')\n",
    "plt.title('Numerical deviation of orbital radius over time')\n",
    "plt.grid(True)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "684fdf40",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_10_0.png)\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_10_1.png)\n",
    "    \n",
    "\n",
    "\n",
    "### Interpretation of Q2\n",
    "This is a simulation of an earth-like planet around the sun using 2D Verlet integration. We start the planet initially at R = 149.6 x 10^11 m in the x direction.\n",
    "We have the initial velocity perpendicular to R in order to keep the orbit in a circular trajectory. Our first plot shows the trajectory of the planet around the sun and we see we have an almost perfect circular orbit.\n",
    "Consequently, we can see that the integration here conserves the angular momentum. Our second plot is the distance of the planet from the sun against time.\n",
    "We can see this varies, due to numerical errors; however, the effect is minimal since our maximum deviation is clearly much less than the distance between the Earth and the Sun.\n",
    "\n",
    "# Q3\n",
    "\n",
    "In this section we will confirm that our simulated orbit generates a closed loop, given the initial conditions of an Earth like planet`.\n",
    "\n",
    "We will also examine the total energy of the Earth throughout it's orbit, which is expected to remain constant.\n",
    "\n",
    "Is the orbit a closed loop?\n",
    "First off, let's check we have the correct initial conditions.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bd531ea8",
   "metadata": {},
   "outputs": [],
   "source": [
    "print('')\n",
    "print(f'r0 = {[r0[0] , r0[1]]}m = [R,0]m')\n",
    "print(f'v0 = {[v0[0],v0[1]]}m/s ≈ [0,29800]m/s ')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e74833a9",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "    \n",
    "    r0 = [np.float64(149600000000.0), np.float64(0.0)]m = [R,0]m\n",
    "    v0 = [np.float64(0.0), np.float64(29782.72894968018)]m/s ≈ [0,29800]m/s \n",
    "\n",
    "\n",
    "So, $\\mathbf{r}_0$ = R$\\mathbf{\\hat{x}}$, and $\\mathbf{v}_0$ ≈ 29.8$\\frac{\\text{km}}{\\text{s}}$$\\mathbf{\\hat{y}}$\n",
    "\n",
    "Now we know our initial conditions are correct, we can check to see if our orbit is closed.\n",
    "\n",
    "To do this we can take a closer look at the start and end points of our plot.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d34f29d0",
   "metadata": {},
   "outputs": [],
   "source": [
    "start_r=np.array([r[0][0],0])\n",
    "end_r=np.array([r[len(t)-1][0],r[len(t)-1][1]])\n",
    "#Defines the start and end position for simulated orbit\n",
    "\n",
    "plt.figure()\n",
    "plt.grid(True)\n",
    "plt.plot(r[:,0],r[:,1], label='Planet Trajectory')\n",
    "plt.scatter(start_r[0],0,color='green',s=70,label='Start')\n",
    "plt.scatter(end_r[0], end_r[1],color='red',s=70,label='End')\n",
    "plt.xlabel('x(m)')\n",
    "plt.ylabel('y(m)')\n",
    "plt.title('Endpoints of Simulated Orbit')\n",
    "plt.legend(loc='upper right')\n",
    "plt.xlim(R-1e11,R+1e11)\n",
    "plt.ylim(-.5e9,.5e9)\n",
    "plt.show()\n",
    "#Same plot from Q2. Have adjusted x and y axis limits to zoom in on start and end point.\n",
    "\n",
    "print(f'Our Starting Position = {start_r} and our Ending Position = {end_r} (in metres)')\n",
    "Close_error=lag.norm(start_r-end_r) #distance between start and end in m\n",
    "Orbit_length= 2 * np.pi * R #circumfernece of expected orbit\n",
    "Percentage_close_error=Close_error/Orbit_length*100 #computes percentage difference between expected vs total distance travelled in orbit\n",
    "print(f'The distance error between start and end = {Close_error:.2} m')\n",
    "print(f'Compared to the total length of orbit this generates a percentage error = {Percentage_close_error:.5f} %')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7c082d07",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_16_0.png)\n",
    "    \n",
    "\n",
    "\n",
    "    Our Starting Position = [1.496e+11 0.000e+00] and our Ending Position = [ 1.49599971e+11 -9.32357924e+07] (in metres)\n",
    "    The distance error between start and end = 9.3e+07 m\n",
    "    Compared to the total length of orbit this generates a percentage error = 0.00992 %\n",
    "\n",
    "\n",
    "Overall, the start and endpoints are very close compared to the scale of the orbit, so it is fair to say our simulation generates a closed loop. The error presented can be mainly attributed to the length of our simulation, which was approximated to 365.25 days.\n",
    "\n",
    "### Is Energy Conserved?\n",
    "\n",
    "We now look at the energy of the system and how it varies. Given that we are assuming the orbit is circular, we would expect that both the kinetic and potential energy remian constant.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "31091c87",
   "metadata": {},
   "outputs": [],
   "source": [
    "def System_energy(r,v,m_sun=m_sun,m_earth=m_earth): #Inputs are the position vand velocity vectors. Mass inputs are optional.\n",
    "    Kinetic = 0.5 * m_earth * np.dot(v,v)\n",
    "    Potential = -G  * m_earth * m_sun / lag.norm(r)\n",
    "    Total = Kinetic + Potential\n",
    "    return Kinetic, Potential, Total\n",
    "#Have defined this as a function so we can reuse in Q4 if wanted. Returns kinetic, potential and total energy of Earth at any given point.\n",
    "\n",
    "Energy=np.zeros((N,3)) #stores kinetic pootential and total energy at each point in simulatted orbit using the for loop.\n",
    "for i in range(N):\n",
    "    r_current=r[i]\n",
    "    v_current=v[i]\n",
    "    Energy[i] = System_energy(r_current,v_current,m_sun,m_earth)\n",
    "\n",
    "\n",
    "\n",
    "t_days=t/(24*hr1) #to be used as x axis in many plots\n",
    "\n",
    "plt.figure()\n",
    "plt.plot(t_days,Energy[:,0], label=('Kinetic'))\n",
    "plt.plot(t_days,Energy[:,1] , label='Potential')\n",
    "plt.plot(t_days,Energy[:,2],label='Total')\n",
    "plt.xlabel('Time (Days)')\n",
    "plt.ylabel('Energy (J)')\n",
    "plt.title('Conservation of Energies')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "plt.show()\n",
    "#plots all three energies against time in days.\n",
    "\n",
    "fig,ax=plt.subplots(nrows=1, ncols=2, figsize=(12,6))\n",
    "ax1=ax[0]\n",
    "\n",
    "\n",
    "ax1.plot(t_days,Energy[:,2],label='Total Energy')\n",
    "max_en=max(Energy[:,2])\n",
    "min_en=min(Energy[:,2])\n",
    "en_range=abs(max_en-min_en)\n",
    "ax1.set_title('Close up of Total Energy over Time')\n",
    "ax1.set_ylabel('Energy (J)')\n",
    "ax1.set_xlabel('Time (Days)')\n",
    "ax1.set_ylim(min_en-en_range*0.2,max_en+en_range*0.2)\n",
    "ax1.grid(True)\n",
    "ax1.legend(loc='upper right')\n",
    "#this is a graph of the total energy but heavily zoomed in on the y axis\n",
    "\n",
    "ax2=ax[1] \n",
    "T_Energy_Change_Percentage=np.array([(Energy[i][2]-Energy[0][2])/Energy[0][2]*100 for i in range(len(t))]) #calculates percentage error against initial energy\n",
    "ax2.plot(t_days,T_Energy_Change_Percentage,label='Total energy percentage change')\n",
    "ax2.plot(t_days, [(max_en - Energy[0][2])/Energy[0][2]*100 for i in range(len(t))],linestyle='--',color='r', label='Max absolute energy percentage error')\n",
    "ax2.set_title('Percentage Change of Total Energy')\n",
    "ax2.set_xlabel('Time (Days)')\n",
    "ax2.set_ylabel('Percentage Change from Starting Value (%)')\n",
    "ax2.grid(True)\n",
    "ax2.legend()\n",
    "plt.show()\n",
    "#graph shows percentage error of total energy only\n",
    "\n",
    "\n",
    "print(f'Our maximum absloute energy percentage error is {max(abs(T_Energy_Change_Percentage))} % ~ {max(abs(T_Energy_Change_Percentage)):.12f} %')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f591d598",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_19_0.png)\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_19_1.png)\n",
    "    \n",
    "\n",
    "\n",
    "    Our maximum absloute energy percentage error is 6.834088693098004e-12 % ~ 0.000000000007 %\n",
    "\n",
    "\n",
    "We have a very small error margin here, which is most likely cause by the fact our verlet algorithm is a numerical aproximation.\n",
    "\n",
    "As a result, we can conclude total energy does remain constant for our simulation.\n",
    "\n",
    "### Analytical derivation of initial speed.\n",
    "\n",
    "Since we are assuming the orbit is circular, we can use the circular motion equation:\n",
    "$$ F = \\frac{m v^2 }{R}    $$\n",
    "We can also consider Newton's equation of motion for the Earth and the Sun:\n",
    "$$ F = \\frac{GMm}{R^2} $$\n",
    "These forces must be equal, allowing us to iset the equations equal to each other:\n",
    "$$ \\frac{m v^2 }{R} = \\frac{GMm}{R^2} $$\n",
    "Now rearrange for v:\n",
    "$$ mv^2 = \\frac{GMm}{R} $$\n",
    "$$ v^2 = \\frac{GM}{R^2} $$\n",
    "$$ v = \\sqrt{\\frac{GM}{R}} $$\n",
    "$$ v = \\sqrt{\\frac{6.67348e-11 \\times 1.988420392e30 }{149.6e9}} ≈ 29.7827 km/s  $$\n",
    "\n",
    "### Q4\n",
    "\n",
    "In this part we keep the initial position of the planet fixed and vary only the magnitude of\n",
    "the tangential initial velocity. Using the velocity Verlet method, we simulate the resulting\n",
    "orbits for several different choices of the initial speed. By doing this we can observe how\n",
    "the orbit changes from a bounded ellipse to an unbounded hyperbolic trajectory as the total\n",
    "energy increases.\n",
    "\n",
    "For the cases that remain elliptical, we compute the perihelion, aphelion, semi–major axis,\n",
    "semi–minor axis, and eccentricity. As we increase the initial velocity, the trajectory no\n",
    "longer returns, allowing us to identify the escape velocity numerically. We then compare\n",
    "this numerical value to the theoretical escape speed.\n",
    "\n",
    "#### Import required libraries and define constants\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "600e0936",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Physical constants\n",
    "G = 6.67430e-11\n",
    "M = 1.989e30                 # mass of the Sun (kg)\n",
    "R = 1.496e11                 # 1 AU (m)\n",
    "\n",
    "# Circular velocity at radius R\n",
    "v_circ = np.sqrt(G*M/R)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f21f4834",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "#### Define the gravitational acceleration \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b37acb78",
   "metadata": {},
   "outputs": [],
   "source": [
    "def acceleration(r):\n",
    "    x, y = r\n",
    "    dist = np.sqrt(x**2 + y**2)\n",
    "    factor = -G*M / (dist**3)\n",
    "    return np.array([factor*x, factor*y])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "020559df",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "#### Implement the velocity Verlet integrator\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "681f1192",
   "metadata": {},
   "outputs": [],
   "source": [
    "def verlet(r0, v0, dt, steps):\n",
    "    r = np.zeros((steps, 2))\n",
    "    v = np.zeros((steps, 2))\n",
    "    r[0] = r0\n",
    "    v[0] = v0\n",
    "\n",
    "    a = acceleration(r0)\n",
    "\n",
    "    for i in range(1, steps):\n",
    "        r[i] = r[i-1] + v[i-1]*dt + 0.5*a*(dt**2)\n",
    "        a_new = acceleration(r[i])\n",
    "        v[i] = v[i-1] + 0.5*(a + a_new)*dt\n",
    "        a = a_new\n",
    "\n",
    "    return r, v"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eda523f4",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "#### Function to compute orbital parameters for elliptical trajectories\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cab73814",
   "metadata": {},
   "outputs": [],
   "source": [
    "def orbital_parameters(r):\n",
    "    dist = np.sqrt(r[:,0]**2 + r[:,1]**2)\n",
    "    P = np.min(dist)\n",
    "    A = np.max(dist)\n",
    "    a = (A + P) / 2\n",
    "    b = np.sqrt(A * P)\n",
    "    e = (A - P) / (A + P)\n",
    "    return P, A, a, b, e"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2fd22f3a",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "#### Simulate trajectories for several choices of $\\lambda$\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a9f98646",
   "metadata": {},
   "outputs": [],
   "source": [
    "lambdas = [0.6, 0.8, 1.0, 1.2, 1.4, 1.45]\n",
    "\n",
    "dt = 2000\n",
    "steps = 20000\n",
    "\n",
    "r0 = np.array([R, 0])\n",
    "results = {}\n",
    "\n",
    "for lam in lambdas:\n",
    "    v0 = np.array([0, lam * v_circ])\n",
    "    r, v = verlet(r0, v0, dt, steps)\n",
    "    results[lam] = r"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "06008628",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "#### Plot the resulting trajectories\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9b7fc901",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(7,7))\n",
    "\n",
    "for lam, r in results.items():\n",
    "    plt.plot(r[:,0], r[:,1], label=f\"λ={lam}\")\n",
    "\n",
    "plt.scatter([0],[0], color='yellow', s=250, label='Sun')\n",
    "plt.title(\"Orbits for Different Initial Velocities\")\n",
    "plt.xlabel(\"x (m)\")\n",
    "plt.ylabel(\"y (m)\")\n",
    "plt.axis(\"equal\")\n",
    "plt.legend()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dd683f2b",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_35_0.png)\n",
    "    \n",
    "\n",
    "\n",
    "#### Compute orbital parameters for the eliptical cases\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "071dcda4",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Elliptical Orbit Parameters:\\n\")\n",
    "for lam in [0.6, 0.8, 1.0, 1.2]:\n",
    "    P, A, a, b, e = orbital_parameters(results[lam])\n",
    "    print(f\"λ = {lam}\")\n",
    "    print(f\"  Perihelion P = {P:.3e} m\")\n",
    "    print(f\"  Aphelion  A = {A:.3e} m\")\n",
    "    print(f\"  Semi-major axis a = {a:.3e} m\")\n",
    "    print(f\"  Semi-minor axis b = {b:.3e} m\")\n",
    "    print(f\"  Eccentricity ε = {e:.4f}\\n\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f6a3bc0a",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "    Elliptical Orbit Parameters:\n",
    "    \n",
    "    λ = 0.6\n",
    "      Perihelion P = 3.284e+10 m\n",
    "      Aphelion  A = 1.496e+11 m\n",
    "      Semi-major axis a = 9.122e+10 m\n",
    "      Semi-minor axis b = 7.009e+10 m\n",
    "      Eccentricity ε = 0.6400\n",
    "    \n",
    "    λ = 0.8\n",
    "      Perihelion P = 7.040e+10 m\n",
    "      Aphelion  A = 1.496e+11 m\n",
    "      Semi-major axis a = 1.100e+11 m\n",
    "      Semi-minor axis b = 1.026e+11 m\n",
    "      Eccentricity ε = 0.3600\n",
    "    \n",
    "    λ = 1.0\n",
    "      Perihelion P = 1.496e+11 m\n",
    "      Aphelion  A = 1.496e+11 m\n",
    "      Semi-major axis a = 1.496e+11 m\n",
    "      Semi-minor axis b = 1.496e+11 m\n",
    "      Eccentricity ε = 0.0000\n",
    "    \n",
    "    λ = 1.2\n",
    "      Perihelion P = 1.496e+11 m\n",
    "      Aphelion  A = 3.847e+11 m\n",
    "      Semi-major axis a = 2.671e+11 m\n",
    "      Semi-minor axis b = 2.399e+11 m\n",
    "      Eccentricity ε = 0.4400\n",
    "    \n",
    "\n",
    "\n",
    "#### Construct an energy criterion and determine escape velocity\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69133e47",
   "metadata": {},
   "outputs": [],
   "source": [
    "def energy(v0):\n",
    "    return 0.5 * v0**2 - G*M/R\n",
    "\n",
    "vels = np.linspace(0.8*v_circ, 2*v_circ, 200)\n",
    "energies = np.array([energy(v) for v in vels])\n",
    "\n",
    "idx = np.where(energies > 0)[0][0]\n",
    "v_escape_num = vels[idx]\n",
    "\n",
    "print(\"Numerical escape velocity:\", v_escape_num/1000, \"km/s\")\n",
    "\n",
    "v_escape_theory = np.sqrt(2*G*M/R)\n",
    "print(\"Theoretical escape velocity:\", v_escape_theory/1000, \"km/s\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "96d79322",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "    Numerical escape velocity: 42.153537932937844 km/s\n",
    "    Theoretical escape velocity: 42.12786542722697 km/s\n",
    "\n",
    "\n",
    "Both the simulated trajectories and the computed energies show that increasing the initial\n",
    "velocity gradually changes the orbit from a closed ellipse to an escape trajectory. The\n",
    "numerical escape velocity is found to be approximately 42 km/s, which agrees closely\n",
    "with the theoretical value of about 42.1 km/s. This confirms that the velocity Verlet\n",
    "method captures the correct energy behaviour for this system.\n",
    "\n",
    "# Introduction to Q9\n",
    "\n",
    "In Question 9 we were asked to simulate solar eclipses in a slightly simplified model of our solar system. A few assumptions allows us to make our modelling slightly simpler.\n",
    "\n",
    "As well as this, we are given the criteria for an eclipse.\n",
    "\n",
    "Initially we are given physical constants, such as the mass and radius of the earth, sun and moon as well as the gravitational constant G, initial conditions at 00:00:00, 21st of June 2010, Newton's Equations of motion and the velocity verlet algorithm.\n",
    "\n",
    "# Modelling Assumptions and their Shortfalls.\n",
    "\n",
    "Throughout this project we have to have some modelling assumptions that allow us to make our calculations, these come with consequences which are listed below:\n",
    "\n",
    "### Assume we are in a heliocentric reference frame\n",
    "\n",
    "- (The sun is in the center and stationary). In reality the gravity from other planetary objects in the solar system causes the sun to move and orbit the barycentre (the common centre of gravity of the solar system) so barycentric reference frame would have been more accurate.\n",
    "\n",
    "### Assume the ommition of other planetary bodies. \n",
    "\n",
    "- This influences the orbit of the earth and the moon (and the sun but it's more of an issue of the reference frame!)\n",
    "\n",
    "### (Implicitly) Assume Celestial bodies are perfectly spherical, uniform bodies. (Assumed by given radius and mass) \n",
    "\n",
    "- This throws off the shadow geometry that we use to predict eclipses later.\n",
    "\n",
    "### (Implicitly) Assume Newtonian Gravity only included\n",
    "\n",
    "- (Relativity is not mentioned).\n",
    "\n",
    "### Assume the velocity verlet algorithm is completely accurate.\n",
    "\n",
    "- It isn't, infact the error grows in proportion with the (time step)^{3}. So as the simulation progresses for long periods of time, estimates will become more inaccurate.\n",
    "\n",
    "### Assume that the Umbra length and radius as well as Penumbra radius formulas are exact\n",
    "\n",
    "- They are an approximation\n",
    "\n",
    "\n",
    "# Code Overview:\n",
    "\n",
    "We are given initial positions and velocities of the Earth and the Moon in a heliocentric reference frame. This implies that we can initialise the position vector of the Sun as the zero vector in three dimensions.\n",
    "\n",
    "## Acceleration of the Earth and Moon\n",
    "\n",
    "Directly from Newton's Equations, we can derive an equation for the acceleration of the Earth and the Moon and as acceleration is the second derivative of position with respect to time this becomes a differential equation for position.\n",
    "\n",
    "Force of Earth:\n",
    "\\begin{align*}\n",
    "m_e \\frac{d^2 \\vec{r_{e}}}{dt^2}\n",
    "= G\\, m_e m_s \\frac{ \\vec{r_s} - \\vec{r_e} }{ |\\vec{r_s} - \\vec{r_e}|^3 } + G\\, m_e m_m \\frac{ \\vec{r_m} - \\vec{r_e} }{ |\\vec{r_m} - \\vec{r_e}|^3 }\n",
    "\\end{align*}\n",
    "Force of the Moon:\n",
    "\\begin{align*}\n",
    "m_m \\frac{d^2 \\vec{r_{m}}}{dt^2}\n",
    "= G\\, m_m m_s \\frac{ \\vec{r_s} - \\vec{r_m} }{ |\\vec{r_s} - \\vec{r_m}|^3 } + G\\, m_m m_e \\frac{ \\vec{r_e} - \\vec{r_m} }{ |\\vec{r_e} - \\vec{r_m}|^3 }\n",
    "\\end{align*}\n",
    "\n",
    "Dividing by $m_e$ and $m_m$ in each equation respectively and factorising gives us two second-order differential equations to solve in terms of position or an equation for acceleration.\n",
    "\n",
    "Acceleration of the Earth:\n",
    "\\begin{align*}\n",
    "\\frac{d^2 \\vec{r_{e}}}{dt^2}\n",
    "= G\\,(m_s \\frac{ \\vec{r_s} - \\vec{r_e} }{ |\\vec{r_s} - \\vec{r_e}|^3 } + m_m \\frac{ \\vec{r_m} - \\vec{r_e} }{ |\\vec{r_m} - \\vec{r_e}|^3 })\n",
    "\\end{align*}\n",
    "Acceleration of the Moon:\n",
    "\\begin{align*}\n",
    "\\frac{d^2 \\vec{r_{m}}}{dt^2}\n",
    "= G\\,(m_s \\frac{ \\vec{r_s} - \\vec{r_m} }{ |\\vec{r_s} - \\vec{r_m}|^3 } + m_e \\frac{ \\vec{r_e} - \\vec{r_m} }{ |\\vec{r_e} - \\vec{r_m}|^3 })\n",
    "\\end{align*}\n",
    "\n",
    "This formula is what the functions accel_earth(rE, rM) and accel_moon(rE, rM) apply. (The arguments rE and rM being the position of the Earth and Moon respectively)\n",
    "\n",
    "## The Velocity Verlet Algorithm\n",
    "\n",
    "This algorithm is a numerical second order method of solving a differential equation. The equations are given by the booklet and programmed as the function verlet(rE, vE, rM, vM, dt):\n",
    "\n",
    "\\begin{align*}\n",
    "r_{k+1} = r_k + v_kdt + \\frac{1}{2}\\frac{d^{2}\\vec{r_k}}{dt^2}dt^{2}\n",
    "\\end{align*}\n",
    "\\begin{align*}\n",
    "v_{k+1} = v_k + \\frac{1}{2}(\\frac{d^{2}\\vec{r_k}}{dt^2} + \\frac{d^{2}{\\vec{r}}_{k+1}}{dt^2})dt\n",
    "\\end{align*}\n",
    "notice that we use the second derivative of position which is just acceleration hence we can use our acceleration function within the velocity verlet function.\n",
    "\n",
    "## Computing the Geometry of our model\n",
    "\n",
    "Using acceleration and the Velocity Verlet algorithm we can compute the geometry of our model, and the resulting shadows.\n",
    "\n",
    "Let S be the Sun and M be the Moon, since sunlight comes from the Sun we can say the vector $\\vec{SM}$ is in the direction of sunlight (since sunlight comes from the Sun) and shadows are just the absence of light, they travel in the same direction. Converting this to a unit vector gives us the direction of the shadow axis:\n",
    "\\begin{align*}\n",
    "\\text{Direction of Shadow} = \\frac{\\vec{SM}}{||\\vec{SM}||}\n",
    "\\end{align*}\n",
    "Now we want to find out how much of the Earth lies in the direction of the shadow, using this we can find out if Earth is in the shadow cast by the Sun. as $\\vec{a} \\cdot \\vec{b}$ = $\\lVert \\vec{a} \\rVert \\lVert \\vec{b} \\rVert \\cos{\\theta}$ when $\\lVert \\vec{b} \\rVert = 1$ then this gives us the shadow's projection, how much of vector **a** lies in the direction of **b** (the shadow axis) by $\\vec{a} \\cdot \\vec{b}$ = $\\lVert \\vec{a} \\rVert \\cos{\\theta}$ Now because we have length of the projection, multiplying it by the shadow direction gives us the projection of the Earth onto the shadow axis. Intuitively, this projection is the side such that imagine the plane in which the Moon and the Earth exist, the hypotenuse of this triangle is the $\\vec{ME}$ and the adjacent side is the projection, the angle is formed at the Moon. As this is the case, we can work out the perpendicular displacement from the Earth to the shadow axis by doing $\\vec{ME}$ - projection and then by taking the magnitude gives us the perpendicular distance. Why is this important? Because it tells us how much of the Earth will be covered by shadow. Large perpendicular distances tell us that the shadow is unlikely to intersect Earth but a small perpendicular distance tells us that more of the Earth is covered by the shadow.\n",
    "\n",
    "## Testing for an Eclipse\n",
    "\n",
    "We can now test for an eclipse using this knowledge. Since we have the criteria for an eclipse, all we need to test is that there exists a portion of Earth that exists in either the umbra or penumbra. There exist approximate formulas for the Umbra Length, the Umbra Radius and the Penumbra Radius (We will assume they are exact as they are a very good approximation).\n",
    "\\begin{align*}\n",
    "\\text{Umbra Length} = \\frac{d_{sm} r_m}{r_{s} - r_{m}}\n",
    "\\end{align*}\n",
    "\\begin{align*}\n",
    "\\text{Umbra Radius} = r_m\\bigg(1-\\frac{d_{me}}{L}\\bigg)\n",
    "\\end{align*}\n",
    "\\begin{align*}\n",
    "\\text{Penumbra Radius} = r_m\\bigg(1+\\frac{d_{me}}{L}\\bigg)\n",
    "\\end{align*} \n",
    "where:\\\n",
    "$d_{sm}$ = distance from the Sun to the Moon \\\n",
    "$d_{me}$ = distance from the Moon to the Earth\\\n",
    "$r_s$ = radius of the Sun\\\n",
    "$r_m$ = radius of the Moon \\\n",
    "(Veras D. 2019)\n",
    "\n",
    "From the criteria of an eclipse, we know that a total eclipse is when the Earth intersects the umbral shadow. If the Earth intersects the penumbral shadow but not the umbral shadow then it is a partial or annular eclipse. A partial eclipse is when the umbral shadow exists but does not intersect Earth, but the Earth does lie in the penumbra.\n",
    "\\\n",
    "If on the other hand the umbra can't reach the Earth but does lie in the penumbral shadow then it is an annular eclipse (the Moon blocks the Sun but not completely and is in the center so you see an annulus). If it doesn't intersect either then it's not an eclipse.\n",
    "\\\n",
    "We can form the following logic and turn it into code by using if statements:\n",
    "\n",
    "\\begin{align*}\n",
    "\\text{Total Eclipse}: d_p < r_u + r_e \\text{ and } r_u > 0\n",
    "\\end{align*}\n",
    "\\begin{align*}\n",
    "\\text{Annular Eclipse}: d_p < r_p + r_e \\text{ and } r_u < 0\n",
    "\\end{align*}\n",
    "\\begin{align*}\n",
    "\\text{Partial Eclipse}: d_p < r_p + r_e \\text{ and } r_u > 0\n",
    "\\end{align*}\n",
    "where:\\\n",
    "$d_p$ = perpendicular distance of the Earth to the shadow axis.\\\n",
    "$r_u$ = Radius of the Umbra\\\n",
    "$r_p$ = Radius of the penumbra\n",
    "\n",
    "## The Rough Scan\n",
    "\n",
    "We technically have enough to run a computation as to where the eclipses may lie, but it will be incredibly computationally expensive. We choose to run 2 scans instead. A scan to check for eclipses using necessary but not sufficient conditions to determine if an eclipse can occur that is significantly less computationally expensive than a full scan.\n",
    "\n",
    "We choose to use 2 conditions to whittle down candidates.\n",
    "\n",
    "### 1. The Moon is between the Earth and the Sun\n",
    "\n",
    "- The angle that the vector $\\vec{MS}$ and $\\vec{ME}$ needs to form is 180 degrees. It's less computationally expensive to compute the cosine of the angle as we can use the vector dot product to compute the cosine of the angle. and the cosine of 180 degrees corresponds to -1 so instead of having to use an arccos function we can just directly compare the cosine of the angle.\n",
    "\\\n",
    "- To be completely exact we should check for $\\cos{\\theta}=-1$ however instead we check for $\\cos{\\theta}<-0.995$ this is to account for approximations made by our model. Initially this was programmed to be -0.9999 however the tolerance was reduced to be -0.995 as the code omitted partial eclipses in the scan.\n",
    "\n",
    "### 2. The Moon is close to the Ecliptic Plane.\n",
    "\n",
    "Initially we programmed the code without this condition, and the amount of possible candidates shot up to a couple thousand candidates instead of a few hundred. This condition helped us reduce the amount of false positives significantly.\n",
    "\\\n",
    "Firstly, what is the ecliptic plane? It is the plane in which the Moon must intersect to be an eclipse, that is the plane in which the Earth is orbiting the Sun in. We can calculate the normal to this plane by considering the initial velocity and initial position vector of the Earth, we know these two vectors are coplanar, hence by taking the cross product we can get the normal of the plane. Dividing this by its magnitude gives us the unit normal vector of the plane.\n",
    "\n",
    "\\begin{align*}\n",
    "h_E = \\vec{r_e} \\times \\vec{v_e} \\implies \\hat{h}_E = \\frac{h_E}{\\lVert h_E \\rVert}\n",
    "\\end{align*}\n",
    "\n",
    "Using this we can define the ecliptic plane by the vectors that satisfy $r \\cdot \\hat{h}_E = 0$ since the vector $\\hat{h}_E$ is a unit vector, taking the dot product of the position vector of the Moon and the unit normal of the ecliptic plane gives us the projection of the Moon onto the ecliptic plane, telling us how far the Moon is from the ecliptic plane. Ideally, we accept vectors such that $|r \\cdot \\hat{h}_E| = 0$ however to account for approximations we accept vectors such that $|r \\cdot \\hat{h}_E| < \\text{tolerance}$ Intersection points to the ecliptic plane are called nodes, hence we've named in the code the tolerance as nodeTolerance. The value we chose was an acceptable balance between computational cost and accuracy.\n",
    "\\\n",
    "If at time t the geometry adheres to both of these conditions we append the time to a list of times. We then integrate using the velocity verlet algorithm and check at the next time step. (Veras D. 2019)\n",
    "\n",
    "## Cleaning the list\n",
    "\n",
    "We then clean the list, removing times that correspond to the same eclipse. This will significantly reduce computation time by checking that the time is not the same as in the eclipses estimates list or within a day of the previous time.\n",
    "\n",
    "## The Fine Scan\n",
    "\n",
    "The fine scan is where we expend our computational resources to get an accurate estimate as to where our eclipses lie.\\\n",
    "Firstly from our cleaned list of times of eclipse estimates we check the times around it by a day, and then check the times around it in fine time steps.\n",
    "But we have to check the position by integrating from our initial time and then getting to our region that we are checking, we integrate in coarse time steps outside the region we are concerned about (dt = 1800) we chose dt = 1800 in this region because any less and we significantly increase computation time and any higher and we decrease accuracy, dt = 1800 is a good compromise. Within the region we are concerned about our dt=10 which gives us a very accurate approximation of the geometry of our system, within the system we use the spatialGeometry function that we have defined to check every time step within the range that we are concerned about and check for the lowest perpendicular distance between the shadow axis and the Earth the lowest perpendicular distance will be our estimate for our central time. We append this to a list as well as the distance from the Moon to the Sun and the distance from the Moon to the Earth as well as the time at which this occurs. \n",
    "\n",
    "## Printing our eclipses\n",
    "\n",
    "With our list, we input the elements of the list into our eclipse test function to find out what type of eclipse the fine scan list has given us.\n",
    "\n",
    "\n",
    "# Additional Library Imports:\n",
    "\n",
    "- Imported tqdm from the tqdm library to have a progress bar as the rough and fine scan's progress.\n",
    "- Imported datetime and timedelta from the datetime library to convert seconds into dates.\n",
    "- Imported time to compute the runtime of the program.\n",
    "\n",
    "# Comparison of our Results to Real data (from NASA):\n",
    "| Date       | Our Type | NASA Type | Our Time (approx) | NASA Central Time (TD) | Notes                                    |\n",
    "| :--------- | :-------: | :-------: | :----------------: | :--------------------: | :-----------------------------------   |\n",
    "| 2010-07-11 |   Total   |   Total   |      19:38:20      |        19:34:38        | **~+4 min**                            |\n",
    "| 2011-11-25 |  Partial  |  Partial  |      06:49:30      |        06:21:24        | **~+28 min**                           |\n",
    "| 2012-05-21 |  Annular  |  Annular  |      00:37:50      |    23:53:53 (May 20)   | **~+44 min (Across Midnight)**          |\n",
    "| 2012-11-13 |   Total   |   Total   |      23:07:20      |        22:12:55        | **~+54 min**                           |\n",
    "| 2013-05-10 |  Annular  |  Annular  |      01:32:50      |        00:26:20        | **~+66 min**                           |\n",
    "| 2013-11-03 |  Annular  |   Hybrid  |      14:07:10      |        12:47:36        | **~+79 min, Hybrid Not classified**   | \n",
    "| 2015-03-20 |  Partial  |   Total   |      11:38:10      |        09:46:47        | **~+111 min, type mismatch**           |\n",
    "| 2015-09-13 |  Annular  |  Partial  |      10:00:00      |        06:55:19        | **~+185 min, type mismatch**           |\n",
    "| 2016-03-09 |   Total   |   Total   |      04:12:00      |        01:58:19        | **~+134 min**                          |\n",
    "| 2016-09-01 |  Annular  |  Annular  |      11:42:40      |        09:08:02        | **~+155 min**                          |\n",
    "| 2017-02-26 |  Annular  |  Annular  |      17:27:00      |        14:54:32        | **~+153 min**                          |\n",
    "| 2017-08-21 |   Total   |   Total   |      21:31:50      |        18:26:40        | **~+185 min**                          |\n",
    "| 2019-07-02 |   Total   |   Total   |      23:20:00      |        19:24:07        | **~+236 min**                          |\n",
    "| 2019-12-26 |  Annular  |  Annular  |      08:54:20      |        05:18:53        | **~+215 min**                          |\n",
    "| 2020-06-21 |  Annular  |  Annular  |      10:54:20      |        06:41:15        | **~+253 min**                          |\n",
    "| 2020-12-14 |   Total   |   Total   |      20:23:00      |        16:14:39        | **~+248 min**                          |\n",
    "| 2021-06-10 |  Annular  |  Annular  |      15:11:20      |        10:43:06        | **~+268 min**                          |\n",
    "| 2021-12-04 |   Total   |   Total   |      12:12:30      |        07:34:38        | **~+278 min**                          |\n",
    "| 2023-04-20 |  Annular  |   Hybrid  |      09:33:40      |        04:17:55        | **~+315 min, Hybrid Not Classified**  |\n",
    "| 2023-10-14 |  Annular  |  Annular  |      23:17:50      |        18:00:40        | **~+317 min**                          |\n",
    "| 2024-04-09 |   Total   |   Total   |      00:03:30      |        18:18:29        | **~+6 hrs (Across Midnight)**          |\n",
    "| 2024-10-03 |  Annular  |  Annular  |      00:23:20      |        18:46:13        | **~+5.5 hrs**                          |\n",
    "| 2025-03-29 |   Total   |  Partial  |      16:56:10      |        10:48:36        | **~+6 hrs, type mismatch**             |\n",
    "\n",
    "(Espenak, 2014)\n",
    "\n",
    "The error increase from start to finish can be attributed to the error of the velocity verlet algorithm being proportional to $(dt)^3$ as well as other modelling assumptions. The classification is correct for most eclipses aside from a select few cases. Below is a plot for the error growth:\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7ddcffd9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run this cell first\n",
    "data = [\n",
    "    (2010.53,  4/60),      # year, error hours\n",
    "    (2011.90, 28/60),\n",
    "    (2012.38, 44/60),\n",
    "    (2012.87, 54/60),\n",
    "    (2013.36, 66/60),\n",
    "    (2013.84, 79/60),\n",
    "    (2015.22, 111/60),\n",
    "    (2015.70, 185/60),\n",
    "    (2016.19, 134/60),\n",
    "    (2016.67, 155/60),\n",
    "    (2017.16, 153/60),\n",
    "    (2017.64, 185/60),\n",
    "    (2019.50, 236/60),\n",
    "    (2019.98, 215/60),\n",
    "    (2020.47, 253/60),\n",
    "    (2020.95, 248/60),\n",
    "    (2021.44, 268/60),\n",
    "    (2021.92, 278/60),\n",
    "    (2023.30, 315/60),\n",
    "    (2023.78, 317/60),\n",
    "    (2024.27, 360/60),\n",
    "    (2024.76, 330/60),\n",
    "    (2025.24, 360/60),\n",
    "]\n",
    "\n",
    "df = pd.DataFrame(data, columns=[\"year\", \"err_hours\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dbb0d274",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(8,5))\n",
    "plt.plot(df[\"year\"], df[\"err_hours\"])\n",
    "plt.xlabel(\"Year\")\n",
    "plt.ylabel(\"Error (hours)\")\n",
    "plt.title(\"Timing error of our model vs NASA\")\n",
    "plt.grid()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1c607a9d",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "\n",
    "    \n",
    "![png](output_48_0.png)\n",
    "    \n",
    "\n",
    "\n",
    "## Findings from Q9\n",
    "\n",
    "In Question 9 we successfully simulated the orbits of the Earth and the Moon in a heliocentric reference frame under Newtonian gravity and the velocity verlet algorithm. Using our method we were able to correctly predict 23 solar eclipses to within a few hours of the eclipses actually occuring with only a few mismatches to the labels of the eclipses. The ability to solve the question demonstrates how we can relatively accurately predict solar eclipses using average computational power.\\\n",
    "\\\n",
    "Below is the code we used for Q9:\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0d01622",
   "metadata": {},
   "outputs": [],
   "source": [
    "G = 6.67348e-11\n",
    "\n",
    "m_sun = 1.988420392e30\n",
    "m_earth = 5.972000000e24\n",
    "m_moon = 7.345828157e22\n",
    "\n",
    "r_sun = 696340e3\n",
    "r_earth = 6371e3\n",
    "r_moon = 1737e3\n",
    "\n",
    "# ======= Initial Conditions @ 21/6/2010 00:00:00 (All Given in a Heliocentric Reference Frame) =========== \n",
    "\n",
    "rE0 = np.array([-0.012083728, -1.394770664, -0.604680716]) * 1e11\n",
    "rM0 = np.array([-0.015537064, -1.395982236, -0.605576290]) * 1e11\n",
    "\n",
    "vE0 = np.array([ 2.930141099, -0.032094528, -0.013869403]) * 1e4 \n",
    "vM0 = np.array([ 2.967343467, -0.121872473, -0.051163801]) * 1e4 \n",
    "\n",
    "rS = np.zeros(3) # Sun Position fixed at the Origin\n",
    "\n",
    "# ================ Maths pertaining to the Ecliptic Plane ========================\n",
    "\n",
    "hE = np.cross(rE0, vE0) # The Normal Vector to the Ecliptic Plane\n",
    "eclN = hE / lag.norm(hE) # The Unit Normal Vector to the Ecliptic Plane\n",
    "\n",
    "# ======= Acceleration Functions (Provided Directly from Newton's Equations) ================\n",
    "\n",
    "def accel_earth(rE,rM):\n",
    "    rES = rS - rE # Vector going from Earth to Sun\n",
    "    a = G * m_sun * rES / lag.norm(rES)**3\n",
    "\n",
    "    rEM = rM - rE # Vector going from Earth to Moon\n",
    "    a += G * m_moon * rEM / lag.norm(rEM)**3\n",
    "\n",
    "    return a\n",
    "\n",
    "def accel_moon(rE,rM):\n",
    "    rMS = rS - rM # Vector going from Moon to Sun\n",
    "    a = G * m_sun * rMS / lag.norm(rMS)**3\n",
    "\n",
    "    rME = rE - rM #Vector going from Moon to Earth\n",
    "    a += G * m_earth * rME / lag.norm(rME)**3\n",
    "\n",
    "    return a\n",
    "\n",
    "# ======== Velocity Verlet Integration ============\n",
    "\n",
    "# Velocity Verlet Integration has an error proportional to (dt)^3 so as the time increases the estimates have a higher error margin\n",
    "\n",
    "def verlet(rE,vE,rM,vM,dt): \n",
    "    \n",
    "    # Current Accelerations\n",
    "    \n",
    "    aE = accel_earth(rE,rM)\n",
    "    aM = accel_moon(rE,rM)\n",
    "    \n",
    "    # Update Positions\n",
    "    \n",
    "    rE_np1 = rE + vE * dt + 0.5 * aE * dt**2\n",
    "    rM_np1 = rM + vM * dt + 0.5 * aM * dt**2\n",
    "\n",
    "    # Update Accelerations\n",
    "\n",
    "    aE_np1 = accel_earth(rE_np1, rM_np1)\n",
    "    aM_np1 = accel_moon(rE_np1, rM_np1)\n",
    "\n",
    "    # Update Velocities\n",
    "\n",
    "    vE_np1 = vE + 0.5 * (aE + aE_np1) * dt\n",
    "    vM_np1 = vM + 0.5 * (aM + aM_np1) * dt\n",
    "\n",
    "    return rE_np1, vE_np1, rM_np1, vM_np1\n",
    "\n",
    "# ========== Modelling for the Spatial Geometry of planetary motion =================\n",
    "\n",
    "# The purpose of this function is to find whether the earth is inside the shadow cone of the moon.\n",
    "\n",
    "def spatialGeometry(rE, rM): \n",
    "\n",
    "    # Vector Displacements\n",
    "    \n",
    "    rMS = rS - rM # Moon -> Sun Displacement vector\n",
    "    rME = rE - rM # Moon -> Earth Displacement vector\n",
    "\n",
    "    # Scalar Distances \n",
    "    \n",
    "    sMS = lag.norm(rMS) # Sun -> Moon Distance Scalar\n",
    "    sME = lag.norm(rME) # Moon -> Earth Distance Scalar\n",
    "\n",
    "    shadowDirection = -rMS/sMS # Unit Vector in Direction of the Shadow Axis\n",
    "\n",
    "    # Length of Projection\n",
    "\n",
    "    projection_length = np.dot(rME, shadowDirection) # This tells us how far along the shadow axis does the earth lies, as shadowDirection is a unit vector\n",
    "    # a.b = ||a||cos(theta) if b is a unit vector, which shows us that this is in this case rME being projected onto the unit vector of the shadowDirection\n",
    "    \n",
    "    projection = projection_length * shadowDirection # This tells us the component of the Displacement vector that is in the direction of the shadow\n",
    "\n",
    "    pDisp = rME - projection # Perpendicular Displacement Vector\n",
    "    pDist = lag.norm(pDisp) # Perpendicular Distance (This is the minimising distance between the Earth and the Shadow Axis)\n",
    "\n",
    "    return sMS, sME, pDist\n",
    "\n",
    "# ======== Testing for an eclipse ===========\n",
    "\n",
    "def eclipseTest(sMS, sME, pDist, debug=False):\n",
    "\n",
    "    # Umbra cone length\n",
    "    L = sMS * (r_moon / (r_sun - r_moon))\n",
    "\n",
    "    # Radii\n",
    "    umbraR = r_moon * (1 - sME / L) # Umbra Radius\n",
    "    penumbraR = r_moon * (1 + sME / L) # Penumbra Radius\n",
    "    \n",
    "# ------------ debug area ------------------------------\n",
    "    if debug:\n",
    "        print(\"ECLIPSE TEST:\")\n",
    "        print(\" L =\", L)\n",
    "        print(\" umbraR =\", umbraR)\n",
    "        print(\" penumbraR =\", penumbraR)\n",
    "        print(\" pDist =\", pDist)\n",
    "        print()\n",
    "# ----------------------------------------------------\n",
    "    \n",
    "    # For the Moon to completely block the sun the Umbra's Radius MUST be greater than 0\n",
    "    if umbraR > 0:\n",
    "        if pDist < umbraR + r_earth: # We add the Radius of the Earth as the Earth is not a point but approximately a sphere\n",
    "            return \"Total Eclipse\"\n",
    "        if pDist < penumbraR + r_earth: # As the p_dist is greater than the umbra's Radius + the radius of the earth the moon is partially blocking the Sun\n",
    "            return \"Partial Eclipse\"\n",
    "        return None\n",
    "\n",
    "    # Umbra does NOT reach Earth, so you can only have an Annular Eclipse or No Eclipse\n",
    "    else:\n",
    "        if pDist < penumbraR + r_earth: # Moon's shadow is smaller than the light cone of the sun, so creates an annulus\n",
    "            return \"Annular Eclipse\"\n",
    "        return None\n",
    "        \n",
    "# ============ Rough Scan ===================\n",
    "\n",
    "# The purpose of the rough scan is to find out potential candidates for the eclipses, this prevents us from having to run the simulation finely for an insanely long time\n",
    "# to whittle down computational resources, we then proceed by running a fine scan to deal with this.\n",
    "\n",
    "def rough_scan(years=15, dt=300): #dt is in seconds\n",
    "\n",
    "    print(\"Rough Scan has Started\")\n",
    "    \n",
    "    seconds = years * 365.25 * 24 * 3600\n",
    "    steps = int(seconds/dt)\n",
    "\n",
    "    # Initialise Position and Velocity Vectors of the moon to their Initial vectors\n",
    "    \n",
    "    rE, vE = rE0.copy(), vE0.copy()\n",
    "    rM, vM = rM0.copy(), vM0.copy()\n",
    "\n",
    "    \n",
    "    eclipseEstimates = [] # List Containing the Times of our eclipse estimates on our rough scan.\n",
    "\n",
    "    for step in tqdm(range(steps),desc=\"Rough Scan\",unit=\"Steps\"): # Loops through the cases, appending in the list possible candidates for eclipses\n",
    "        t = step * dt\n",
    "\n",
    "        rMS = rS - rM # Vector from moon -> sun\n",
    "        rME = rE - rM # Vector from moon -> earth\n",
    "\n",
    "        cos_angle = np.dot(rMS, rME) / (lag.norm(rMS)*lag.norm(rME)) # This is the angle between the vector from the Moon to the Sun and the vector from the Moon to the Earth.\n",
    "        \n",
    "        colinear = (cos_angle<-0.995) # The colinear check, checks that the 2 vectors are approximately colinear and the vectors are in opposite directions to eachother\n",
    "        # the reason the restriction is to <-0.995 is so that it takes into account the error from the velocity verlet integration.\n",
    "\n",
    "        # Ecliptic Plane Geometry Checks - This Check is necessary to whittle down candidates as to be an eclipse the moon must intersect the ecliptic plane.\n",
    "        # Without this check the number of possible candidates increases by over 10x So this significantly reduces the runtime and increases the accuracy\n",
    "        sEcliptic = abs(np.dot(rM, eclN)) # Distance from Moon to the Ecliptic Plane\n",
    "        nodeTolerance = 3e6 \n",
    "        near_node = (sEcliptic < nodeTolerance) # A node is an intesecting point of the ecliptic plane, this checks that the moon is near the node to a reasonable degree\n",
    "        if colinear and near_node: # All three checks must be successful in order for it to be a possible eclipse.\n",
    "            eclipseEstimates.append(t)\n",
    "\n",
    "        # Integrate to use for next step @ the next time step\n",
    "        rE, vE, rM, vM = verlet(rE, vE, rM, vM, dt)\n",
    "\n",
    "    print(\"Rough Scan Complete\")\n",
    "    \n",
    "    return eclipseEstimates\n",
    "\n",
    "# ========== Fine Scan ===============\n",
    "\n",
    "# Since we already have the rough scan we can use the time values for our rough scan and look through the interval of the rough scan to work out the fine scan times.\n",
    "\n",
    "def fine_scan(tc, window_hr=12, dt=10, dt_skip=300):\n",
    "\n",
    "    # tc = time estimate, which is our center time.\n",
    "    # window_hr = the window either side of tc in which it checks for the time of the solar eclipse in the fine scan\n",
    "    # dt = The time steps within our window\n",
    "    # dt_skip = The time steps outside our window\n",
    "    \n",
    "    t0 = max(0, tc - window_hr*3600) # Start Time (Max to prevent t0 being negative)\n",
    "    t1 = tc + window_hr*3600 # End Time\n",
    "\n",
    "    # Reset Initial Conditions\n",
    "    rE, vE = rE0.copy(), vE0.copy()\n",
    "    rM, vM = rM0.copy(), vM0.copy()\n",
    "\n",
    "    t = 0 # Need to start @ t = 0 to do the integration as it's constantly moving.\n",
    "    jump = 1800 # Jumps of 30 minutes is about optimal for as much accuracy while not sacrificing computational resources\n",
    "    while t < t0 - jump:\n",
    "        rE, vE, rM, vM = verlet(rE, vE, rM, vM, jump)\n",
    "        t += jump\n",
    "\n",
    "    # Then refine with dt_skip to integrate our way closer to t0 with minimal computational resources.\n",
    "    while t < t0:\n",
    "        step_dt = min(dt_skip, t0 - t)\n",
    "        rE, vE, rM, vM = verlet(rE, vE, rM, vM, step_dt)\n",
    "        t += step_dt\n",
    "\n",
    "    \n",
    "    t_ref = sMS_ref = sME_ref = None # Starts off with nothing but then gets appended as better estimation arises.\n",
    "    pDist_ref = 1e20 # Refined Perpendicular Distance Estimate (which will get minimised) We start off super high and work our way down\n",
    "\n",
    "    while t < t1:\n",
    "\n",
    "        sMS, sME, pDist = spatialGeometry(rE,rM) # Computes the Geometry at the current t\n",
    "\n",
    "        if pDist < pDist_ref: # Constantly keeps the most refined estimate for pDist and pDist_ref\n",
    "            pDist_ref = pDist\n",
    "            t_ref = t\n",
    "            sMS_ref = sMS\n",
    "            sME_ref = sME\n",
    "                \n",
    "        # Step Integrator\n",
    "        rE, vE, rM, vM = verlet(rE, vE, rM, vM, dt)\n",
    "        t += dt\n",
    "        \n",
    "    return t_ref, sMS_ref, sME_ref, pDist_ref\n",
    "\n",
    "# ======== Convert seconds to datetime ========\n",
    "\n",
    "initialTime = datetime(2010, 6, 21, 0, 0, 0) # Our Initial Time that we work from provided by the booklet.\n",
    "\n",
    "# Following function converts the seconds into time\n",
    "def dateConversion(t):\n",
    "    return initialTime + timedelta(seconds=t) \n",
    "\n",
    "# ======== Computations ============\n",
    "\n",
    "print(\"Run time has started\")\n",
    "start = time.time() # Starts timing the process\n",
    "rough_times = rough_scan(years=15, dt=3600)\n",
    "print(\"Number of Rough Candidates:\",len(rough_times))\n",
    "\n",
    "cleaned = [] # To avoid duplicate fine_scan calls to save computation time.\n",
    "print(\"Cleaning Rough Scan List\")\n",
    "for t in rough_times:\n",
    "    if not cleaned or abs(t-cleaned[-1]) > 86400: # The abs(t-cleaned[-1]) exists to only have one time to exist to be the representative for the eclipse\n",
    "        cleaned.append(t)\n",
    "\n",
    "rough_times = cleaned # Sets the rough times list as the cleaned list\n",
    "print(f\"Rough Scan list Cleaned to {len(rough_times)} Candidates\")\n",
    "\n",
    "refined_results = [] # List of the refined results\n",
    "\n",
    "print(\"Fine Scan has Started\")\n",
    "\n",
    "for tc in tqdm(rough_times,desc=\"Fine Scan\",unit=\"Candidates\"):\n",
    "    t_ref, sMS, sME, pDist = fine_scan(tc, window_hr=12, dt=10, dt_skip=300)\n",
    "    refined_results.append((t_ref, sMS, sME, pDist)) \n",
    "print(\"Number of fine candidates:\", len(refined_results))    \n",
    "print(\"Fine Scan Complete\")\n",
    "\n",
    "# ======== Extract real eclipses from refined_results ========\n",
    "\n",
    "def extract_eclipses(refined_results, debug=False):\n",
    "    print(\"Extracting Eclipses\")\n",
    "    eclipse_list = [] # The list of eclipses\n",
    "\n",
    "    for (t_ref, sMS, sME, pDist) in refined_results:\n",
    "        etype = eclipseTest(sMS, sME, pDist) # Return the type of eclipse\n",
    "        \n",
    "# --------------------------- debug area ------------------------------------------\n",
    "        if debug:\n",
    "            print(\"t =\",t_ref)\n",
    "            print(\"sMS=\",sMS)\n",
    "            print(\"sME=\",sME)\n",
    "            print(\"pDist =\",pDist)\n",
    "            print(\"eclipseTest =\", etype)\n",
    "            print()\n",
    "# -------------------------------------------------------------------------------------\n",
    "        \n",
    "        if etype is not None: # Eliminates Non-Eclipses to rid false positives\n",
    "            eclipse_list.append((t_ref, etype))\n",
    "\n",
    "    return eclipse_list\n",
    "\n",
    "# =================== Print eclipse list =============================\n",
    "\n",
    "def print_eclipses(eclipse_list):\n",
    "    print(f\"There are {len(eclipses)} predicted eclipses in this time period:\")\n",
    "    print(\"\\nPredicted Eclipses (YYYY / MM / DD):\\n\")\n",
    "    for t, etype in eclipse_list:\n",
    "        print(f\"{dateConversion(t)} | {etype:13}\") # Prints the Date and Time and the type of eclipse\n",
    "\n",
    "\n",
    "eclipses = extract_eclipses(refined_results)\n",
    "print_eclipses(eclipses)\n",
    "print(\"\\nTotal Runtime:\",time.time() - start, \"seconds\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "af016d12",
   "metadata": {},
   "source": [
    "\n",
    "\n",
    "    Run time has started\n",
    "    Rough Scan has Started\n",
    "\n",
    "\n",
    "    Rough Scan: 100%|██████████| 131490/131490 [00:03<00:00, 40751.27Steps/s]\n",
    "\n",
    "\n",
    "    Rough Scan Complete\n",
    "    Number of Rough Candidates: 231\n",
    "    Cleaning Rough Scan List\n",
    "    Rough Scan list Cleaned to 23 Candidates\n",
    "    Fine Scan has Started\n",
    "\n",
    "\n",
    "    Fine Scan:  35%|███▍      | 8/23 [00:09<00:23,  1.56s/Candidates]\n",
    "\n",
    "## References:\n",
    "\n",
    "Espenak, F. (2014) Five Millennium Catalog of Solar Eclipses: -1999 to +3000 (2000 BCE to 3000 CE). NASA Eclipse Web Site. Available at: https://eclipse.gsfc.nasa.gov/SEcat5/SEcatalog.html\n",
    " (Accessed: 27 November 2025).\n",
    "\n",
    "NASA Goddard Space Flight Center (2012) Eclipses and the Moon’s orbit. NASA Eclipse Web Site. Available at: https://eclipse.gsfc.nasa.gov/SEhelp/moonorbit.html\n",
    " (Accessed: 27 November 2025).\n",
    "\n",
    "Veras, D. (2019) ‘Explicit relations and criteria for eclipses, transits, and occultations’, Monthly Notices of the Royal Astronomical Society, 483(3), pp. 3919–3952.\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
